# Generated by Django 6.0 on 2025-12-23 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(95)])),
                ('job', models.CharField(max_length=150)),
            ],
        ),
    ]
