# Generated by Django 6.0 on 2025-12-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalcrew', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
