# Generated by Django 6.0 on 2025-12-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Proffesion',
            field=models.CharField(max_length=150),
        ),
    ]
