# Generated by Django 6.0 on 2025-12-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalpages', '0002_alter_hospital_proffesion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='name',
            new_name='user',
        ),
    ]
