# Generated by Django 6.0 on 2025-12-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalpages', '0003_rename_name_hospital_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
