# Generated by Django 6.0 on 2025-12-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicology', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
