# Generated by Django 6.0 on 2025-12-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicology', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
